## Exercise 1.01: Loading a Sample Dataset and Calculating the Mean

In this exercise, we will be loading the normal_distribution.csv dataset and calculate the mean of each row and each column with it.   
Our dataset will have several rows each containing floating point numbers around 100 with a standard deviation of 5.

Just to refresh your knowledge, a Gaussian normal distribution resembles this plot:   

[Normal Distribution ](https://en.wikipedia.org/wiki/Normal_distribution)   
![](https://upload.wikimedia.org/wikipedia/commons/9/9e/Normal_Distribution_NIST.gif)   


In our case, the vertical bar in the middle is the number 100.

#### Loading our dataset

In [2]:
pip install numpy

                                              0.0/15.8 MB ? eta -:--:--
                                              0.0/15.8 MB ? eta -:--:--
                                             0.0/15.8 MB 330.3 kB/s eta 0:00:48
                                             0.0/15.8 MB 262.6 kB/s eta 0:01:01
                                             0.1/15.8 MB 292.6 kB/s eta 0:00:54
                                             0.1/15.8 MB 273.8 kB/s eta 0:00:58
                                             0.1/15.8 MB 262.6 kB/s eta 0:01:00
                                             0.1/15.8 MB 262.6 kB/s eta 0:01:00
                                             0.1/15.8 MB 276.8 kB/s eta 0:00:57
                                             0.1/15.8 MB 298.5 kB/s eta 0:00:53
                                             0.1/15.8 MB 277.4 kB/s eta 0:00:57
                                             0.1/15.8 MB 293.9 kB/s eta 0:00:54
                                             0.2/15.8 MB

In [3]:
# importing the necessary dependencies
import numpy as np

In [5]:
# loading the Dataset
dataset = np.genfromtxt('normal_distribution.csv', delimiter=',')

In [6]:
# looking at the dataset
dataset

array([[ 99.14931546, 104.03852715, 107.43534677,  97.85230675,
         98.74986914,  98.80833412,  96.81964892,  98.56783189],
       [ 92.02628776,  97.10439252,  99.32066924,  97.24584816,
         92.9267508 ,  92.65657752, 105.7197853 , 101.23162942],
       [ 95.66253664,  95.17750125,  90.93318132, 110.18889465,
         98.80084371, 105.95297652,  98.37481387, 106.54654286],
       [ 91.37294597, 100.96781394, 100.40118279, 113.42090475,
        105.48508838,  91.6604946 , 106.1472841 ,  95.08715803],
       [101.20862522, 103.5730309 , 100.28690912, 105.85269352,
         93.37126331, 108.57980357, 100.79478953,  94.20019732],
       [102.80387079,  98.29687616,  93.24376389,  97.24130034,
         89.03452725,  96.2832753 , 104.60344836, 101.13442416],
       [106.71751618, 102.97585605,  98.45723272, 100.72418901,
        106.39798503,  95.46493436,  94.35373179, 106.83273763],
       [ 96.02548256, 102.82360856, 106.47551845, 101.34745901,
        102.45651798,  98.7476749

---

#### After loading our dataset

To get a quick overview on our dataset we want to print out the "shape" of it.   
This will give us an output of the form (rows, columns)

In [7]:
# printing the shape of our dataset
dataset.shape

(24, 8)

In [8]:
# calculating the mean for the first row
np.mean(dataset[0])

100.177647525

In [9]:
# calculating the mean for the first column
np.mean(dataset[:, 0])

99.76743510416668

In [10]:
# mean for each row
np.mean(dataset, axis=1)

array([100.17764752,  97.27899259, 100.20466135, 100.56785907,
       100.98341406,  97.83018578, 101.49052285,  99.75332252,
       101.89845125,  99.77973914, 101.013081  , 100.54961696,
        98.48256886,  98.49816126, 101.85956927,  97.05201872,
       102.62147483, 101.21177037,  99.58777968,  98.96533534,
       103.85792812, 101.89050288,  99.07192574,  99.34233101])

In [11]:
# mean for each col
np.mean(dataset, axis=0)

array([ 99.7674351 ,  99.61229127, 101.14584656, 101.8449316 ,
        99.04871791,  99.67838931,  99.7848489 , 100.44049274])

In [12]:
# calculating the mean for the whole matrix
np.mean(dataset)

100.16536917390624

When looking at the mean values we can really nicely see the effect of calculating the mean of several vaules taken from a normal distribution.   
If we had even more data we would get even close to 100.